
on:
  schedule:
  - cron: '0 * * * *'
name: Excavator
jobs:
  excavate:
    name: Excavator
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: Excavator
      uses: Ash258/Scoop-GithubActions@stable-win
      env:
        GITH_EMAIL: brett@brettb.xyz
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SKIP_UPDATED: '1'